name: constructor-env

channels:
  - conda-forge

dependencies:
  - conda >=23.11.0
  - conda-build
  - conda-libmamba-solver
  - conda-standalone >=23.11.0,!=24.11.0
  - constructor >=3.6.0
  - fmt !=10.2.0
  - menuinst >= 2.4.0
